CREATE TABLE `APP_AUTH` (
  `APP_ID` varchar(32) NOT NULL,
  `APP_NAME` varchar(128) DEFAULT NULL,
  `TYPE` varchar(32) DEFAULT NULL COMMENT '1:web端；2:APP端',
  `APP_SECRET` varchar(32) DEFAULT NULL,
  `APP_DESC` varchar(256) DEFAULT NULL,
  `APP_PROD` varchar(32) DEFAULT NULL,
  `SECURITY_LEVEL` varchar(1) DEFAULT 'L',
  `CALLBACK_DOMAIN` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`APP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8